export interface VehicleData {
  recordedattime: number,
  lineref: string,
  dataframeref: string,
  datedvehiclejourneyref: string,
  directionname: string,
  originref: string,
  destinationref: string,
  originaimeddeparturetime: number,
  destinationaimedarrivaltime: number,
  monitored: boolean,
  incongestion: boolean,
  longitude: number,
  latitude: number,
  blockref: string,
  vehicleref: string,
  visitnumber: number,
  vehicleatstop: boolean,
  destinationdisplay: string,
  aimedarrivaltime: number,
  expectedarrivaltime: number,
  aimeddeparturetime: number,
  expecteddeparturetime: number,
  destinationdisplay_sv: string,
  destinationdisplay_en: string,
  __tripref: string
}